mommy does github actions~ 💙

diff --git a/src/main/sh/mommy b/src/main/sh/mommy
--- a/src/main/sh/mommy
+++ b/src/main/sh/mommy
@@ -75,11 +75,6 @@ MOMMY_FORBIDDEN_WORDS=""
 # whitespace character. A list is represented by a string, consisting of the entries separated by `/`s. A list does not
 # have leading or trailing `/`s.
 
-# Joins all lists from the input arguments into a single list.
-lists_join() {
-    printf "%s/" "$@" | head -c -1
-}
-
 # Outputs `0` if the string `$1` contains any of the substrings in the list `$2`, and outputs `1` otherwise.
 list_contains_any() {
     if [ "$2" = "" ]; then
@@ -118,15 +113,19 @@ list_sanitize() {
         list="${list#*/}"
     done
 
-    printf "%s" "$sanitized_list" | head -c -1
+    printf "%s" "${sanitized_list%?}"
     return 0
 }
 
 # Writes a random entry from the list in stdin to stdout.
 list_choose() {
     list="$(cat)/"
-    count="$(printf "%s" "$list" | grep -o "/" | wc -l)"
-    idx="$(shuf -i 1-"$count" -n 1)"
+    count="$(printf "%s" "$list" | tr -cd "/" | wc -c)"
+    if [ -x "$(command -v shuf)" ]; then
+        idx="$(shuf -i 1-"$count" -n 1)"
+    else
+        idx="$(jot -r 1 1 "$count")"
+    fi
 
     i="1"
     while [ -n "$list" ]; do
@@ -158,17 +157,16 @@ color_cat() {
 # Reads stdin; if `$1` is `0`, the first character on each line is changed to lowercase, if `$1` is `1`, the first
 # character on each line is changed to uppercase, and otherwise nothing is changed; and writes to stdout.
 capitalize_lines() {
-    entry="$(cat)"
     if [ "$1" = "0" ]; then
         mapping="tolower"
     elif [ "$1" = "1" ]; then
         mapping="toupper"
     else
-        printf "%s" "$entry"
+        cat
         return 0
     fi
 
-    printf "%s" "$entry" | awk "{ print $mapping(substr(\$0, 1, 1)) substr(\$0, 2) }"
+    cat | awk "{ print $mapping(substr(\$0, 1, 1)) substr(\$0, 2) }"
     return 0
 }
 
@@ -187,7 +185,7 @@ fill_template() {
     caregiver=$(printf "%s" "$3" | list_sanitize | list_choose)
     suffix=$(printf "%s" "$4" | list_sanitize | list_choose)
 
-    output=$(cat |
+    output=$(printf "%s\n" "$(cat)" |
                  sed -e "s/%%SWEETIE%%/$sweetie/g" -e "s/%%THEIR%%/$their/g" -e "s/%%CAREGIVER%%/$caregiver/g" |
                  capitalize_lines "$5" |
                  sed -e "1h;2,\$H;\$!d;g" -e "s/^\n*//" -e "s/\n*$//")
@@ -225,14 +223,14 @@ if [ -n "$MOMMY_OPT_HELP" ]; then
     local_man_path="$(dirname -- "$0")/../resources/mommy.1"
 
     if [ -f "$local_man_path" ]; then
-        man -l "$local_man_path" | cat
-        return 0
+        man "$local_man_path" | cat
+        exit 0
     elif [ -f "$global_man_path" ]; then
         man mommy | cat
-        return 0
+        exit 0
     else
-        echo "could not find the manual page~" | g_fill_template >&2
-        return 1
+        echo "could not find the manual page~" >&2
+        exit 1
     fi
 else
     if [ -n "$MOMMY_OPT_EVAL" ]; then
@@ -246,11 +244,11 @@ else
     fi
 
     if [ $command_exit_code -eq 0 ] && [ "$MOMMY_COMPLIMENTS_ENABLED" = "1" ]; then
-        templates=$(lists_join "$MOMMY_COMPLIMENTS" "$MOMMY_COMPLIMENTS_EXTRA")
+        templates="$MOMMY_COMPLIMENTS/$MOMMY_COMPLIMENTS_EXTRA"
     elif [ $command_exit_code -ne 0 ] && [ "$MOMMY_ENCOURAGEMENTS_ENABLED" = "1" ]; then
-        templates=$(lists_join "$MOMMY_ENCOURAGEMENTS" "$MOMMY_ENCOURAGEMENTS_EXTRA")
+        templates="$MOMMY_ENCOURAGEMENTS/$MOMMY_ENCOURAGEMENTS_EXTRA"
     else
-        return $command_exit_code
+        exit $command_exit_code
     fi
 
     color=$(printf "%s" "$MOMMY_COLOR" | list_sanitize | list_choose)
@@ -261,5 +259,5 @@ else
         list_choose |
         fill_template "$MOMMY_SWEETIE" "$MOMMY_THEIR" "$MOMMY_CAREGIVER" "$MOMMY_SUFFIX" "$MOMMY_CAPITALIZE" |
         color_cat "$color" >&2
-    return $command_exit_code
+    exit $command_exit_code
 fi
